[package]
description = "Derive macros for `documented`"
edition = "2021"
license = "MIT"
name = "documented-derive"
repository = "https://github.com/cyqsimon/documented"
version = "0.4.0"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.35"
syn = "2.0.48"
