[package]
edition.workspace = true
name = "documented-test"
publish = false
rust-version.workspace = true
version.workspace = true

[dev-dependencies]
documented = { path = "../lib" }

[features]
customise = ["documented/customise"]
default = ["customise"]
